/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentregistrationsystem;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;


public class Login extends javax.swing.JFrame {

    LinkedList<Student> studList;
   
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        studList = FileController.loadStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTitle = new JLabel();
        formContainer = new JPanel();
        studIDLabel = new JLabel();
        passwordLabel = new JLabel();
        loginBtn = new JButton();
        passwordField = new JTextField();
        idField = new JTextField();
        registerBtn = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        loginTitle.setFont(new Font("SF UI Display", 1, 36)); // NOI18N
        loginTitle.setText("Login");

        studIDLabel.setText("Student ID");

        passwordLabel.setText("Password");

        loginBtn.setBackground(new Color(0, 102, 255));
        loginBtn.setForeground(new Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        GroupLayout formContainerLayout = new GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(formContainerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formContainerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField)
                    .addComponent(idField)
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addGroup(formContainerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(studIDLabel)
                            .addComponent(passwordLabel))
                        .addGap(0, 274, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, formContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loginBtn, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(registerBtn, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        formContainerLayout.setVerticalGroup(formContainerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studIDLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(formContainerLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(loginTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(formContainer, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(loginTitle)
                .addGap(34, 34, 34)
                .addComponent(formContainer, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String id = idField.getText();
        String password = passwordField.getText();
        try {
            if (id.length() <= 0) {
                throw new FormException("Please Enter Your ID");
            }
            
            if (password.length() < 6) {
                throw new FormException("Password should be more than 6 Characters");
            }
            
            boolean found = false;
            Student loggedIn = new Student();
            
            for(Student current : studList) {
                if (current.id.equalsIgnoreCase(id) && current.password.equals(password)) {
                    found = true;
                    loggedIn = current;
                }
            }
            
            if (!found) {
                throw new FormException("Invalid ID and Password Combination, try Again");
            }
            
            this.dispose();
            if (loggedIn != null && found) {
                Profile profileApp = new Profile(loggedIn);
                profileApp.setVisible(true);
                
            }
            
            
        }catch(FormException e) {
            JOptionPane.showMessageDialog(this, e.message, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        this.dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatDarculaLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel formContainer;
    private JTextField idField;
    private JButton loginBtn;
    private JLabel loginTitle;
    private JTextField passwordField;
    private JLabel passwordLabel;
    private JButton registerBtn;
    private JLabel studIDLabel;
    // End of variables declaration//GEN-END:variables
}
